apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "canine.fullname" . }}
  namespace: {{ .Values.namespace.name }}
  labels:
    {{- include "canine.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "canine.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "canine.selectorLabels" . | nindent 8 }}
    spec:
      {{- if .Values.volumes.dockerSocket.enabled }}
      volumes:
        - name: dockersock
          hostPath:
            path: {{ .Values.volumes.dockerSocket.hostPath }}
      {{- end }}
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          envFrom:
            - secretRef:
                name: {{ include "canine.fullname" . }}-env
          env:
            - name: LOCAL_MODE
              value: {{ .Values.app.localMode | quote }}
            - name: PORT
              value: {{ .Values.app.port | quote }}
            - name: APP_HOST
              value: {{ .Values.app.host | quote }}
          ports:
            - name: http
              containerPort: {{ .Values.app.port }}
              protocol: TCP
            - name: aux
              containerPort: {{ .Values.app.auxPort }}
              protocol: TCP
          {{- if .Values.volumes.dockerSocket.enabled }}
          volumeMounts:
            - name: dockersock
              mountPath: {{ .Values.volumes.dockerSocket.hostPath }}
          {{- end }}
          livenessProbe:
            tcpSocket:
              port: http
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 3
          readinessProbe:
            tcpSocket:
              port: http
            initialDelaySeconds: 10
            periodSeconds: 5
            timeoutSeconds: 3
            failureThreshold: 3
          {{- if .Values.resources }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          {{- end }}
