{{- if .Values.postgresql.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "canine.fullname" . }}-postgres
  namespace: {{ .Values.namespace.name }}
  labels:
    {{- include "canine.labels" . | nindent 4 }}
    app.kubernetes.io/component: postgres
spec:
  type: ClusterIP
  selector:
    {{- include "canine.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: postgres
  ports:
    - port: 5432
      targetPort: 5432
      protocol: TCP
      name: postgres
{{- end }}
