apiVersion: v1
kind: Secret
metadata:
  name: {{ include "canine.fullname" . }}-env
  namespace: {{ .Values.namespace.name }}
  labels:
    {{- include "canine.labels" . | nindent 4 }}
type: Opaque
stringData:
  DATABASE_URL: "postgres://{{ .Values.postgresql.auth.username }}:{{ .Values.postgresql.auth.password }}@{{ include "canine.fullname" . }}-postgres:5432"
  REDIS_URL: "redis://{{ include "canine.fullname" . }}-redis:6379"
  CANINE_USERNAME: {{ .Values.app.username | quote }}
  CANINE_PASSWORD: {{ .Values.app.password | quote }}
