apiVersion: v1
kind: Service
metadata:
  name: {{ include "canine.fullname" . }}
  namespace: {{ .Values.namespace.name }}
  labels:
    {{- include "canine.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  selector:
    {{- include "canine.selectorLabels" . | nindent 4 }}
  ports:
    - name: http
      port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      {{- if and (eq .Values.service.type "NodePort") .Values.service.nodePort }}
      nodePort: {{ .Values.service.nodePort }}
      {{- end }}
    - name: aux
      port: {{ .Values.service.auxPort }}
      targetPort: aux
      protocol: TCP
      {{- if and (eq .Values.service.type "NodePort") .Values.service.auxNodePort }}
      nodePort: {{ .Values.service.auxNodePort }}
      {{- end }}
